name: PR Counter

on:
  pull_request:
    types: [opened, closed]

jobs:
  count-prs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Count PRs by User
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { data: pulls } = await github.rest.pulls.list({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'all',
              per_page: 100
            });

            const counts = {};
            for (const pr of pulls) {
              const user = pr.user.login;
              counts[user] = (counts[user] || 0) + 1;
            }

            function getLevel(points) {
              if (points >= 10) return "Level 3";
              if (points >= 7) return "Level 2";
              if (points >= 3) return "Level 1";
              return "Beginner";
            }

            const results = {};
            for (const user in counts) {
              const prCount = counts[user];
              let points = 0;

              if (prCount >= 10) points = 10;
              else if (prCount >= 7) points = 7;
              else if (prCount >= 3) points = 3;

              results[user] = { PRs: prCount, Points: points, Level: getLevel(points) };
            }

            console.log("PR Levels:", results);
