name: PR Level Points

on:
  pull_request:
    types: [opened, synchronize, reopened, labeled]

jobs:
  assign-points:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR labels
        id: check
        run: |
          echo "LEVEL=0" >> $GITHUB_ENV
          labels=$(jq -r '.pull_request.labels[].name' < "$GITHUB_EVENT_PATH")
          echo "Labels: $labels"

          if echo "$labels" | grep -iq "level 1"; then
            echo "LEVEL=3" >> $GITHUB_ENV
          elif echo "$labels" | grep -iq "level 2"; then
            echo "LEVEL=7" >> $GITHUB_ENV
          elif echo "$labels" | grep -iq "level 3"; then
            echo "LEVEL=10" >> $GITHUB_ENV
          fi

      - name: Comment points on PR
        uses: peter-evans/create-or-update-comment@v3
        with:
          token: ${{ secrets.GH_TOKEN }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            🎯 PR Points Assigned: **${{ env.LEVEL }}**
            (Based on PR label: Level 1 → 3, Level 2 → 7, Level 3 → 10)
